### ISSUE TITLE
DOM nodes inserted/remove by ng-if bug

### ISSUE THREAD

**Issue by Attrash-Islam** [wix/angular-viewport-watch#10]
Hi Shahar,
You've a great plugin right here

I used it in multiple projects, and one of the problems I've encounter is that when you've a big list that contains header and inner ng-repeat (I've used ng-repeat-start/end), and you try to click on a button which is closing all the inner ng-repeat by using ng-if without removing the repeater headers (Which also crossing the viewport).

You can see that the first shown header was closed and the others still opened, and when scrolling they all get closed!

I tried to use DOMNodeInserted/DOMNodeRemoved DOM events to try to enable the digests by running the activating function but that didn't help :(

I hope you can help me with that

Thanks
Best Regards,
Islam

**Comment by Attrash-Islam** [comment]
The directive is not working good with ng-repeat-start/end in multiple places as I can see among the examples I use

**Comment by amirgon** [comment]
@Attrash-Islam  I also had issue when using this directive with ng-repeat-start/end.  
A solution I found was to prevent the recursive descent of the scope tree when reaching a nested scope where the directive is used again.  

I changed the directive something like this:

```
            link: function (scope, element, attr) {
                scope.$$viewportWatch = true;
```

...

   ```
                     while (!next && current !== scope) {
                            if (current.$$nextSibling &&
                                !current.$$nextSibling.hasOwnProperty('$$viewportWatch')) {
                                next = current.$$nextSibling;
                            } else {
                                current = current.$parent;
                            }
                        }
```

Then make sure you have `viewport-watch` attribute on both `ng-repeat-start` and `ng-repeat-end`.  
This directive doesn't seem to be maintained any more, otherwise I would have bothered with a pull request...

**Comment by Attrash-Islam** [comment]
Thanks for the feedback
I'm thinking to merge some reactjs components for the performance benefit, because depending on DEPRECATED directive may crash all our most-popular used (ng-repeat) in our ngApps!

Thanks again for your best effort ;)
